# Generated by Django 5.0 on 2023-12-22 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='History',
            new_name='Gift_History',
        ),
    ]
