# Generated by Django 5.0 on 2023-12-24 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_gifts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gift_History',
            new_name='Gift1_History',
        ),
    ]
