# Generated by Django 5.0 on 2024-01-03 12:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_rename_gift_history_gift1_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('name', models.CharField()),
                ('users_id', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), size=None)),
            ],
        ),
    ]
